set(HUNTER_ARCHIVE_BZIP2_OPTION "bz2" PARENT_SCOPE)
set(HUNTER_ARCHIVE_GZIP_OPTION "gz" PARENT_SCOPE)
set(HUNTER_ARCHIVE_LZMA_OPTION "xz" PARENT_SCOPE)

set(HUNTER_ARCHIVE_OPTIONS ${HUNTER_ARCHIVE_BZIP2_OPTION} ${HUNTER_ARCHIVE_GZIP_OPTION} ${HUNTER_ARCHIVE_LZMA_OPTION} PARENT_SCOPE)
