set(HUNTER_ARCHIVE_BZIP2_OPTION "bz2")
set(HUNTER_ARCHIVE_GZIP_OPTION "gz")
set(HUNTER_ARCHIVE_LZMA_OPTION "xz")

set(HUNTER_ARCHIVE_OPTIONS ${HUNTER_ARCHIVE_BZIP2_OPTION} ${HUNTER_ARCHIVE_GZIP_OPTION} ${HUNTER_ARCHIVE_LZMA_OPTION})
